### PR TITLE
Create newhotfix.py

### PR DESCRIPTION
**Pull request by AmirHosseinFallahmanesh**
hello mr @imortezaafshar  please check in this code

### CODE REVIEW

**Comment by saeed23ty** [comment]
alan manam mibinam va mitoonam merge konam

**Comment by imortezaafshar** [comment]
new answer

**Comment by saeed23ty** [comment]
alan manam mibinam va mitoonam merge konam 
@AmirHosseinFallahmanesh

**Comment by imortezaafshar** [comment]
@AmirHosseinFallahmanesh

**Pull request closed without merging**
